### PR TITLE
exception handling

### PR DESCRIPTION
**Pull request by Daha62**
Cought an exception:

yii\base\ErrorException: Trying to get property of non-object in ..humhub/protected/modules/polls/models/Poll.php:257

### CODE REVIEW

**Comment by buddha87** [comment]
hmm, would be interesting how this exception was raised. This only occures if invalid data gets submitted, does it?

**Comment by zhelyabuzhsky** [comment]
I'll answer for @Daha62 =)
Yes, it occures if invalid data were submitted.

**Comment by buddha87** [comment]
ok, thanks but this does only on purpose when manipulating the request right? Just to get sure ;)

**Comment by zhelyabuzhsky** [comment]
yep

**Pull request merged**
