### PR TITLE
"No answered yet" filter not working #60

### PR DESCRIPTION
**Pull request by MasterHans**
**What was done:**
1) Renamed filter keys in view **show**.  Suggesting that 
**'entry_mine'** Filters only content created by the query $user and **"Asked by me"** are the same things.

2) $this->**activeQuery** - depricated since 1.7 replaced it with **$this->streamQuery->query()**
3) $this->streamQuery->filters will be empty and filter **"no answered yet"** will not work until we resolve issue **Needed to add "filters" attribute inside rules method of StreamQuery model #4453** in main humhub repository in the humhub\modules\stream\models\StreamQuery. **load** method of get-parameters works for the model only if rules attribute defined. Here is a link to the mentioned issue:
https://github.com/humhub/humhub/issues/4453

### CODE REVIEW

**Comment by luke-** [comment]
@buddh4 Can you please take a look?

**Comment by buddh4** [comment]
The best way for a 1.3 compatible solution would be:

- Implement a custom [StreamQueryFilter](https://github.com/humhub/humhub/blob/v1.3.0/protected/humhub/modules/stream/models/filters/StreamQueryFilter.php) and add:

```
/**
     * @inheritDoc
     */
    public function formName()
    {
        return $this->formName ?: 'StreamQuery';
    }
```

- Implement a custom [StreamQuery](https://github.com/humhub/humhub/blob/v1.3.0/protected/humhub/modules/stream/models/StreamQuery.php) and extend `$filterHandlers` with your custom filter handler

- Set [StreamAction::$streamQueryClass](https://github.com/humhub/humhub/blob/v1.3.0/protected/humhub/modules/stream/actions/Stream.php#L151) to your custom one.

**Review by buddh4 — CHANGES_REQUESTED** [review]
As I understood this change only works with https://github.com/humhub/humhub/issues/4453 ?

The best way for a 1.3 compatible solution would be:

- Implement a custom [StreamQueryFilter](https://github.com/humhub/humhub/blob/v1.3.0/protected/humhub/modules/stream/models/filters/StreamQueryFilter.php) and add:

```
/**
     * @inheritDoc
     */
    public function formName()
    {
        return $this->formName ?: 'StreamQuery';
    }
```

- Implement a custom [StreamQuery](https://github.com/humhub/humhub/blob/v1.3.0/protected/humhub/modules/stream/models/StreamQuery.php) and extend `$filterHandlers` with your custom filter handler

- Set [StreamAction::$streamQueryClass](https://github.com/humhub/humhub/blob/v1.3.0/protected/humhub/modules/stream/actions/Stream.php#L151) to your custom one.

Also have a look at https://github.com/humhub/humhub/issues/4453#issuecomment-706128424

**Comment by MasterHans** [comment]
@buddh4 all done! Thank you!

**Pull request merged**
